#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help()
{
    
}

COMMAND=""
LOG_FILES=""
GZ_LOG_FILES=""





while ["$#" -gt 0 ]; do
    case "$1" in
    list-tick | pos)
        COMMAND="$1"
        shift
        ;;
    -h)
        print_help
        exit 0
        ;;
    -w)
        WIDTH="$2"
        shift
        shift
        ;;
    *)
        if []; then
            GZ_LOG_FILES="$1 $GZ_LOG_FILES"
        else
            LOG_FILES="$1 $LOG_FILES"
        fi
    esac
done

READ_INPUT="gzip -d -c $GZIP | cat $LOG_FILES - | sort"

READ_FILTERED="eval $READ_INPUT | awk"



